name: Rust

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rustup update
        run: rustup update

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  release:
    runs-on: ${{ matrix.job.os }}
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build

    strategy:
      matrix:
        job:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: i686-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rustup update
        run: rustup update

      - name: Set up toolchain
        run: rustup target add ${{ matrix.job.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.job.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.job.target }}
          path: |
            target/${{ matrix.job.target }}/release/client
            target/${{ matrix.job.target }}/release/client.exe
